package database;

public class GitasDBT {

    public static String    OTOBUSLER = "otobusler_v2",
            HATLAR = "otobus_hatlar",
            ORER_KAYIT = "filo_orer",
            ORER_LOG = "orer_log",
            ORER_EKSEFERLER = "orer_ekseferler",
            ORER_EKSEFER_ONERILERI = "orer_eksefer_onerileri",
            IYS_KAYIT = "filo_iys",
            IYS_KAYIT_LOG = "iys_kayit_log",
            SURUCULER = "soforler",
            FILO_MESAJLAR = "filo_mesajlar",
            FILO_MESAJLAR_GIDEN = "filo_mesajlar_giden",
            CONFIG = "config",
            COOKIES = "filo_cookies",
            ALARMLAR = "alarmlar",
            APP_STATS = "app_stats",
            NOTLAR = "app_notlar_v2",
            NOT_BILDIRIMLERI = "not_bildirimleri",
            PDKS_KAYIT = "pdks_kayit",
            PLAKA_DEGISIMLERI = "app_plaka_degisim_bildirimleri",
            OTOBUS_DURAK_TAKIP = "app_otobus_durak_takip",
            SUNUCU_APP_CONFIG = "sunucu_app_config",
            SUNUCU_APP_HATA_KAYITLARI = "sunucu_app_hata_kayitlari",
            FILO_ORER_DEGISIKLIK_LOG = "filo_orer_degisiklik_log",
            FILO_ORER_ROTASYON = "filo_orer_rotasyon",
            FILO_HIZ_KAYITLARI = "filo_hiz_kayitlari",
            OTOBUS_AKTIF_DURUM = "app_otobus_aktif_durum",
            OTOBUS_ALARM_DATA = "app_alarm_data",
            OTOBUS_ALARM_DATA_GORENLER = "app_alarm_data_gorenler",
            APP_KULLANICILAR = "app_kullanicilar",
            HAT_DURAKLAR = "hat_duraklar";
}
